#!/bin/sh
# Signing a PE/CAB/MSI file with the encrypted private key file in the DER format.
# Requires OpenSSL 1.0.0 or later

. $(dirname $0)/../test_library

# PE file
test_name="031. Signing a PE file with the encrypted private key file in the DER format"
printf "\n%s\n" "$test_name"
if [ -s "test.exe" ]
  then
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
            -pass passme \
           -in "test.exe" -out "test_031.exe"'
    verify_signature "$?" "031" "exe" "sha256sum"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
test_name="032. Signing a CAB file with the encrypted private key file in the DER format"
printf "\n%s\n" "$test_name"
if [ -s "test.ex_" ]
  then
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
            -pass passme \
            -in "test.ex_" -out "test_032.ex_"'
    verify_text "$?" "032" "ex_" "osslsigncode" "ASCII" "sha256sum" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# MSI file
test_name="033. Signing a MSI file with the encrypted private key file in the DER format"
printf "\n%s\n" "$test_name"
if [ -s "sample.msi" ]
  then
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
            -pass passme \
            -in "sample.msi" -out "test_033.msi"'
    verify_signature "$?" "033" "msi" "sha256sum"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
