#!/bin/sh
# Sign a PE/CAB/MSI file with a descryption

. $(dirname $0)/../test_library
script_path=$(pwd)

# PE file
test_name="141. Sign a PE file with a descryption"
printf "\n%s\n" "$test_name"
if [ -s "test.exe" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -n "DESCRYPTION_TEXT" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.exe" -out "test_141.exe"
    verify_signature "$?" "141" "exe" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "DESCRYPTION_TEXT" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
test_name="142. Sign a CAB file with a descryption"
printf "\n%s\n" "$test_name"
if [ -s "test.ex_" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -n "DESCRYPTION_TEXT" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.ex_" -out "test_142.ex_"
    verify_signature "$?" "142" "ex_" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "DESCRYPTION_TEXT" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# MSI file
test_name="143. Sign a MSI file with a descryption"
printf "\n%s\n" "$test_name"
if [ -s "sample.msi" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -n "DESCRYPTION_TEXT" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "sample.msi" -out "test_143.msi"
    verify_signature "$?" "143" "msi" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "DESCRYPTION_TEXT" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
