#!/bin/sh
# Signing a PE file with sha512 set of cryptographic hash functions.

. $(dirname $0)/../test_library

# PE file
test_name="251. Signing a PE file with sha512 set of cryptographic hash functions"
printf "\n%s\n" "$test_name"
if [ -s "test.exe" ]
  then
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha512 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
            -in "test.exe" -out "test_251.exe"'
    verify_signature "$?" "251" "exe" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file

# MSI file

exit 0
