#!/bin/sh
# Remove the signature from the PE/CAB/MSI file.

. $(dirname $0)/../test_library
script_path=$(pwd)

# PE file
test_name="331. Remove the signature from the PE file"
printf "\n%s\n" "$test_name"
if test -s "test.exe"
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.exe" -out "test_331_signed.exe" && \
    ../../osslsigncode remove-signature \
        -in "test_331_signed.exe" -out "test_331.exe"
    verify_signature "$?" "331" "exe" "fail" "@2019-09-01 12:00:00" \
	"sha256sum" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
test_name="332. Remove the signature from the CAB file"
printf "\n%s\n" "$test_name"
if [ -s "test.ex_" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.ex_" -out "test_332_signed.ex_" && \
    ../../osslsigncode remove-signature \
        -in "test_332_signed.ex_" -out "test_332.ex_"
    verify_signature "$?" "332" "ex_" "fail" "@2019-09-01 12:00:00" \
	"sha256sum" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# MSI file
test_name="333. Remove the signature from the MSI file"
printf "\n%s\n" "$test_name"
if test -s "sample.msi"
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "sample.msi" -out "test_333_signed.msi" && \
    ../../osslsigncode remove-signature \
        -in "test_333_signed.msi" -out "test_333.msi"
    verify_signature "$?" "333" "msi" "fail" "@2019-09-01 12:00:00" \
	"sha256sum" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
