#!/bin/sh
# Moving the authenticode signing to the PE/MSI file.

. $(dirname $0)/../test_library

# PE file
test_name="341. Moving the authenticode signing to the PE file"
printf "\n%s\n" "$test_name"
if [ -s "test.exe" ]
  then
    cp "test.exe" "test_341.exe"
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
            -in "test.exe" -out "test_341_signed.exe" && \
        ../../osslsigncode add \
            -in "test_341_signed.exe" -out "test_341.exe"'
    verify_signature "$?" "341" "exe" "sha256sum"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
# Command is not supported for non-PE

# MSI file
test_name="342. Moving the authenticode signing to the MSI file"
printf "\n%s\n" "$test_name"
if [ -s "sample.msi" ]
  then
    cp "sample.msi" "test_342.msi"
    faketime -f '@2019-01-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
            -in "sample.msi" -out "test_342_signed.msi" && \
        ../../osslsigncode add \
            -in "test_342_signed.msi" -out "test_342.msi"'
    verify_signature "$?" "342" "msi" "sha256sum"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
