#!/bin/sh
# Add an unauthenticated blob to the PE/MSI file.

. $(dirname $0)/../test_library
script_path=$(pwd)

# PE file
test_name="361. Add an unauthenticated blob to the PE file"
printf "\n%s\n" "$test_name"
if test -s "test.exe"
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.exe" -out "test_361_signed.exe"
    ../../osslsigncode add \
        -addUnauthenticatedBlob \
        -in "test_361_signed.exe" -out "test_361.exe"
    verify_signature "$?" "361" "exe" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "BEGIN_BLOB" "MODIFY"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
# Command is not supported for non-PE/non-MSI files

# MSI file
test_name="362. Add an unauthenticated blob to the MSI file"
printf "\n%s\n" "$test_name"
if test -s "sample.msi"
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "sample.msi" -out "test_362_signed.msi"
    ../../osslsigncode add \
        -addUnauthenticatedBlob \
        -in "test_362_signed.msi" -out "test_362.msi"
    verify_signature "$?" "362" "msi" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "BEGIN_BLOB" "MODIFY"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
