#!/bin/sh
# Checking SHA256 message digests for 31x-33x tests.

. $(dirname $0)/../test_library
res=0
res=0
skip=0
test_name="361. Checking SHA256 message digests for 31x-33x tests"
printf "\n%s\n" "$test_name"
if test -s "test.exe"
  then
    if test $(cat "sha256sum_exe.log" | cut -d' ' -f1 | uniq | wc -l) -ne 1
      then
        res=1
        cat "sha256sum_exe.log" >> "results.log"
        printf "Non-unique SHA256 message digests found\n" >> "results.log"
      fi
    rm -f "sha256sum_exe.log"
  else
    skip=$(($skip+1))
  fi

if test -s "test.ex_"
  then
    if test $(cat "sha256sum_ex_.log" | cut -d' ' -f1 | uniq | wc -l) -ne 1
      then
        res=1
        cat "sha256sum_ex_.log" >> "results.log"
        printf "Non-unique SHA256 message digests found\n" >> "results.log"
      fi
    rm -f "sha256sum_ex_.log"
  else
    skip=$(($skip+1))
  fi

if test -s "sample.msi"
  then
    if test $(cat "sha256sum_msi.log" | cut -d' ' -f1 | uniq | wc -l) -ne 1
      then
        res=1
        cat "sha256sum_msi.log" >> "results.log"
        printf "Non-unique SHA256 message digests found\n" >> "results.log"
      fi
    rm -f "sha256sum_msi.log"
  else
    skip=$(($skip+1))
  fi

if test $skip -lt 2
  then
    test_result "$res" "$test_name"
  else
    printf "Test skipped\n"
  fi
exit 0
