#!/bin/sh
# Add an authenticode timestamp to the PE/MSI file.

. $(dirname $0)/../test_library
script_path=$(pwd)

# PE file
test_name="371. Add an authenticode timestamp to the PE file"
printf "\n%s\n" "$test_name"
if [ -s "test.exe" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "test.exe" -out "test_371_signed.exe" && \
    ../../osslsigncode add \
        -t http://time.certum.pl/ \
        -in "test_371_signed.exe" -out "test_371.exe"
    verify_signature "$?" "371" "exe" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "Unizeto" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
# Command is not supported for non-PE/non-MSI files

# MSI file
test_name="372. Add an authenticode timestamp to the MSI file"
printf "\n%s\n" "$test_name"
if [ -s "sample.msi" ]
  then
    ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -in "sample.msi" -out "test_372_signed.msi" && \
    ../../osslsigncode add \
        -t http://time.certum.pl/ \
        -in "test_372_signed.msi" -out "test_372.msi"
    verify_signature "$?" "372" "msi" "success" "@2019-09-01 12:00:00" \
	"UNUSED_PATTERN" "ASCII" "Unizeto" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
