#!/bin/sh
# Verify changed file after signing with RFC 3161 timestamping.

. $(dirname $0)/../test_library
script_path=$(pwd)
test_nr=47

if ! grep -q "no libcurl available" "results.log"; then
  for file in ${script_path}/../logs/notsigned/*.*
    do
      name="${file##*/}"
      ext="${file##*.}"
      desc=""
      case $ext in
        "cat") continue;; # Test is not supported for non-PE files
        "msi") continue;; # Test is not supported for non-PE files
        "ex_") continue;; # Test is not supported for non-PE files
        "exe") filetype=PE; format_nr=4 ;;
        "ps1") continue;; # Test is not supported for non-PE files
      esac

      number="$test_nr$format_nr"
      test_name="Verify changed $filetype$desc file after signing with RFC 3161 timestamping"
      printf "\n%03d. %s\n" "$number" "$test_name"

      ../../osslsigncode sign -h sha256 \
        -st "1556668800" \
        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
        -ts http://time.certum.pl/ \
        -ts http://timestamp.digicert.com/ \
        -verbose \
        -in "notsigned/$name" -out "test_$number.$ext"
      result=$?

      verify_signature "$result" "$number" "$ext" "fail" "@2019-09-01 12:00:00" \
        "UNUSED_PATTERN" "Hello world!" "MODIFY"
      test_result "$?" "$number" "$test_name"
    done
  else
    format_nr=0
    number="$test_nr$format_nr"
    test_name="Verify changed file after signing with RFC 3161 timestamping"
    printf "\n%03d. %s\nTest skipped\n" "$number" "$test_name"
  fi

exit 0
