#!/bin/sh
# Verify PE/CAB/MSI file signed with the expired cert.

. $(dirname $0)/../test_library

# PE file
test_name="541. Verify PE file signed with the expired cert"
printf "\n%s\n" "$test_name"
if test -s "test.exe" && ! grep -q "no libcurl available" "results.log"
  then
    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/expired.pem" -key "${script_path}/../certs/key.pem" \
            -t http://time.certum.pl/ \
            -in "test.exe" -out "test_541.exe" 2>> "results.log" 1>&2'
    verify_signature "$?" "541" "exe" "fail" "@2025-01-01 12:00:00" \
	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# CAB file
test_name="542. Verify CAB file signed with the expired cert"
printf "\n%s\n" "$test_name"
if test -s "test.ex_" && ! grep -q "no libcurl available" "results.log"
  then
    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/expired.pem" -key "${script_path}/../certs/key.pem" \
            -t http://time.certum.pl/ \
            -in "test.ex_" -out "test_542.ex_" 2>> "results.log" 1>&2'
    verify_signature "$?" "542" "ex_" "fail" "@2025-01-01 12:00:00" \
	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

# MSI file
test_name="543. Verify MSI file signed with the expired cert"
printf "\n%s\n" "$test_name"
if test -s "sample.msi" && ! grep -q "no libcurl available" "results.log"
  then
    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
        script_path=$(pwd)
        ../../osslsigncode sign -h sha256 \
            -certs "${script_path}/../certs/expired.pem" -key "${script_path}/../certs/key.pem" \
            -t http://time.certum.pl/ \
            -in "sample.msi" -out "test_543.msi"'
    verify_signature "$?" "543" "msi" "fail" "@2025-01-01 12:00:00" \
	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
    test_result "$?" "$test_name"
  else
    printf "Test skipped\n"
  fi

exit 0
